name: Build and Deploy

on:
  push:
    branches: 
      - main 
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generated Environment Variables File
        run: |
          echo "${{ secrets.ENV }}" > .env 
  
          
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: build

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t changhom/awstestimg .
          docker push changhom/awstestimg
          
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo echo "${{ secrets.ENV }} > .env
            sudo docker pull changhom/awstestimg
            sudo docker run --env-file .env -p 8080:8080 changhom/awstestimg
